console.log('es8'.padStart(2));          // 'es8'
console.log('es8'.padStart(5));          // '  es8'
console.log('es8'.padStart(6, 'woof'));  // 'wooes8'
console.log('es8'.padStart(14, 'wow'));  // 'wowwowwowwoes8'
console.log('es8'.padStart(7, '0'));     // '0000es8'
console.log('es8'.padEnd(2));          // 'es8'
console.log('es8'.padEnd(5));          // 'es8  '
console.log('es8'.padEnd(6, 'woof'));  // 'es8woo'
console.log('es8'.padEnd(14, 'wow'));  // 'es8wowwowwowwo'
console.log('es8'.padEnd(7, '6'));     // 'es86666'